 * Swagger Petstore
 *
 * Contact: apiteam@swagger.io
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.

package io.swagger.client.model;
import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.client.model.Animal;
import java.util.List;
import java.util.UUID;

 * MixedPropertiesAndAdditionalPropertiesClass

  @JsonProperty("uuid")

  private OffsetDateTime dateTime = null;
  @JsonProperty("map")

    this.uuid = uuid;
  }
   /**
   * @return uuid
  @ApiModelProperty(value = "")
    return uuid;

    this.uuid = uuid;

    this.dateTime = dateTime;
  }
   /**
   * @return dateTime
  @ApiModelProperty(value = "")
    return dateTime;

    this.dateTime = dateTime;

    this.map = map;
  }
  public MixedPropertiesAndAdditionalPropertiesClass putMapItem(String key, Animal mapItem) {
      this.map = new HashMap<String, Animal>();
    this.map.put(key, mapItem);
  }
   /**
   * @return map
  @ApiModelProperty(value = "")
    return map;

    this.map = map;

  @Override
  if (this == o) {
  }
    return false;
    MixedPropertiesAndAdditionalPropertiesClass mixedPropertiesAndAdditionalPropertiesClass = (MixedPropertiesAndAdditionalPropertiesClass) o;
    ObjectUtils.equals(this.dateTime, mixedPropertiesAndAdditionalPropertiesClass.dateTime) &&
  }
  @Override
    return ObjectUtils.hashCodeMulti(uuid, dateTime, map);

  @Override
    StringBuilder sb = new StringBuilder();
    
    sb.append("    dateTime: ").append(toIndentedString(dateTime)).append("\n");
    sb.append("}");
  }
  /**
   * (except the first line).
  private String toIndentedString(java.lang.Object o) {
      return "null";
    return o.toString().replace("\n", "\n    ");

