 * Swagger Petstore
 *
 * Contact: apiteam@swagger.io
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.

package io.swagger.client.model;
import org.apache.commons.lang3.ObjectUtils;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.client.model.Animal;
/**
 */
public class Cat extends Animal {
  private Boolean declawed = null;
  public Cat declawed(Boolean declawed) {
    return this;

   * Get declawed
  **/
  public Boolean isDeclawed() {
  }
  public void setDeclawed(Boolean declawed) {
  }

  public boolean equals(java.lang.Object o) {
    return true;
  if (o == null || getClass() != o.getClass()) {
  }
    return ObjectUtils.equals(this.declawed, cat.declawed) &&
  }
  @Override
    return ObjectUtils.hashCodeMulti(declawed, super.hashCode());

  @Override
    StringBuilder sb = new StringBuilder();
    sb.append("    ").append(toIndentedString(super.toString())).append("\n");
    sb.append("}");
  }
  /**
   * (except the first line).
  private String toIndentedString(java.lang.Object o) {
      return "null";
    return o.toString().replace("\n", "\n    ");

