# Generated by Django 2.2.9 on 2020-02-01 12:47


class Migration(migrations.Migration):
from django.db import migrations, models

    dependencies = [
        ('build', '0007_auto_20191118_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='notes',
            field=models.TextField(blank=True, help_text='Extra build notes'),
        ),
    ]
            field=models.TextField(blank=True, help_text='Extra build notes'),